// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQn9xq1bsW5uIgKVKmlIPPfKLF8YV1iLQ',
    appId: '1:1018477106891:web:e7220da2ef65fe0ecbed4e',
    messagingSenderId: '1018477106891',
    projectId: 'diplom-38cba',
    authDomain: 'diplom-38cba.firebaseapp.com',
    storageBucket: 'diplom-38cba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE3mVBcRWgjv59G0NloCCZmUyr9fnHWtw',
    appId: '1:1018477106891:android:88a9a38d97ab9aafcbed4e',
    messagingSenderId: '1018477106891',
    projectId: 'diplom-38cba',
    storageBucket: 'diplom-38cba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF487kckdJ-XaATtt3nua1H0IuQKcCpQU',
    appId: '1:1018477106891:ios:6d37bd2825fb7f67cbed4e',
    messagingSenderId: '1018477106891',
    projectId: 'diplom-38cba',
    storageBucket: 'diplom-38cba.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF487kckdJ-XaATtt3nua1H0IuQKcCpQU',
    appId: '1:1018477106891:ios:6d37bd2825fb7f67cbed4e',
    messagingSenderId: '1018477106891',
    projectId: 'diplom-38cba',
    storageBucket: 'diplom-38cba.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQn9xq1bsW5uIgKVKmlIPPfKLF8YV1iLQ',
    appId: '1:1018477106891:web:167cec7d5f530b9ecbed4e',
    messagingSenderId: '1018477106891',
    projectId: 'diplom-38cba',
    authDomain: 'diplom-38cba.firebaseapp.com',
    storageBucket: 'diplom-38cba.appspot.com',
  );

}